# Generated by Django 5.1.2 on 2024-10-21 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False, verbose_name='Está pergunta é a correta?')),
                ('points', models.IntegerField(default=0, verbose_name='Pontuação obtida')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionandanswer.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='questionandanswer.response')),
            ],
        ),
    ]
