# Generated by Django 5.1.2 on 2024-10-23 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0004_alter_scoring_user'),
        ('room', '0006_alter_room_options_alter_room_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='text',
            new_name='text_response',
        ),
        migrations.AlterField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='room.room'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='questionandanswer.question'),
        ),
    ]
