# Generated by Django 5.1.2 on 2024-10-23 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswer', '0005_rename_text_response_text_response_and_more'),
        ('room', '0006_alter_room_options_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
            preserve_default=False,
        ),
    ]
