# Generated by Django 5.1.2 on 2024-10-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
    ]
