# Generated by Django 5.1.2 on 2024-10-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_remove_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
