# Generated by Django 5.1.2 on 2024-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
