# Generated by Django 5.1.2 on 2024-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_alter_room_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='Código gerado após salvar a sala...', max_length=6, unique=True),
        ),
    ]
